name: flame_box2d
description: Box2D support for the Flame game engine. This uses the box2d.dart package and provides wrappers and components to be used inside Flame.
version: 0.0.1
homepage: https://github.com/flame-engine/flame_box2d

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flame: '>=0.23.0 <1.0.0'
  box2d_flame: ^0.4.6
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.9.4
