name: sprite_body
description: Flame sample game showcasing sprite_body_components

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame: '>=0.23.0 <1.0.0'
  flame_box2d:
    path: ../../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/ship.png
